<?php

declare(strict_types=1);

namespace App\Exception;

class EnumErrors
{
    public const NO_ARGUMENT_INPUT_FILE = 'NO_ARGUMENT_INPUT_FILE';
    public const INPUT_FILE_DOES_NOT_EXIST = 'INPUT_FILE_DOES_NOT_EXIST';
    public const INPUT_FILE_CANNOT_BE_READ = 'INPUT_FILE_CANNOT_BE_READ';

    public const BIN_PROVIDER_RESPONSE_ERROR = 'BIN_PROVIDER_RESPONSE_ERROR';
    public const BIN_PROVIDER_RESPONSE_CONTENT_ERROR = 'BIN_PROVIDER_RESPONSE_CONTENT_ERROR';
    public const BIN_PROVIDER_INVALID_URL = 'BIN_PROVIDER_INVALID_URL';

    public const RATE_PROVIDER_INVALID_URL = 'RATE_PROVIDER_INVALID_URL';
    public const RATE_PROVIDER_INVALID_KEY = 'RATE_PROVIDER_INVALID_KEY';
    public const RATE_PROVIDER_RESPONSE_ERROR = 'RATE_PROVIDER_RESPONSE_ERROR';
    public const RATE_PROVIDER_RESPONSE_CONTENT_ERROR = 'RATE_PROVIDER_RESPONSE_CONTENT_ERROR';
    public const RATE_PROVIDER_INVALID_AMOUNT = 'RATE_PROVIDER_INVALID_AMOUNT';
}
